version: "3.4"

services:  
  mongodb_1:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "vaxidrez"
      MONGO_INITDB_ROOT_PASSWORD: "VaxiDrez2005$$"
    ports:
      - 27018:27017
    volumes:
      - mongodb_data1:/data/db
volumes: 
  mongodb_data1:
    driver: local
networks:
  default:
    name: mongodb_1_network
